# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1pbQ1q8Zo3AUcLd5hbf3j02iJ3hiDyc
"""

#area of the circle

a=int(input("enter radius:"))
area = 3.14*a*a
print(area)

import math

def area_of_circle(radius):
    return math.pi*radius*radius

r = float(input("enter radius:"))
if r<0:
    print("radius cant be neg")
else:
    print("area=", area_of_circle(r))