# -*- coding: utf-8 -*-
"""dict of subjects

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1pbQ1q8Zo3AUcLd5hbf3j02iJ3hiDyc
"""

'''wap to enter of marks of 3 sub from user and store in dictionary,one by one'''


subjects = {}
x = int(input("enter marks in phy: "))
subjects.update({"phy": x})

x = int(input("enter marks in math: "))
subjects.update({"math": x})

x = int(input("enter marks in che: "))
subjects.update({"che": x})

print(subjects)