# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMTX5UiNJcyoDlZ9c30z0-KyChst3ygy
"""

#factorial
def factorial(n):
  if(n==1 or n==0): #in python || is not used instead "or" is used
   return 1

  return n*factorial(n-1)

print(factorial(4))

#func to convert usd to inr

def usd_to_inr(usd_amount):
  conversion_rate = 95.680
  inr_amount = conversion_rate*usd_amount
  return inr_amount
price = float(input("enter price in usd:"))
print(usd_to_inr(price))

#func to get the length of a list

items = input("enter the items of list with space:").split()
def get_len_of_list(my_list):
  return len(my_list)

print("length of the list ",get_len_of_list(items))

#len without using len()
items = input("enter the items of list with space:").split()
def get_length(my_list):
  count=0
  for i in my_list: #range takes only integer values
      count +=1
  return count
print("length of the list is ",get_length(items))

#print elements of a list in a single line
students = ["amshu", "siri", "harshi" , "abhi"]
def print_elements(my_list) :
  output = print(my_list)
  return output
print_elements(students)