# -*- coding: utf-8 -*-
"""no of classrooms

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UpWZoYZ6CagFQp-lu9_-C47Wylu6NQXx
"""

"""you are given a list of subjects for students. assume 1 classroom for 1 subject.
 how many classrooms are required by all students"""

subjects = {"python", "java","c++","python","javascript","java","python","java","c++","c"}
a = len(subjects)
print("number of classrooms: ", a)