# -*- coding: utf-8 -*-
"""patterns

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b_-G16C17ldeIy-TpzDNaxIwTdk9TffS
"""

#printing square pattern

n = int(input("enter number of rows:"))
for i in range(n):     #outer loop
 for j in range(n):    #inner loop
  print("*", end=" ") #dont jump into the next line
 print()

#printing icreasing triangle pattern

n = int(input("enter number of rows:"))
for i in range(n):
  for j in range(i+1):
    print("*",end=" ")
  print()

#printing decreasing triangle pattern

n = int(input("enter number of rows:"))
for i in range(n):
  for j in range(n-i):
    print("*", end=" ")
  print()

#right side triangle pattern
n = int(input("enter number of rows:"))
for i in range(n):
  for j in range(n-i):
    print(" ",end=" ")
  for k in range(i+1):
    print("*",end=" ")
  print()

#right side decreasing triangle pattern
n = int(input("enter number of rows:"))
for i in range(n):
  for j in range(i):
    print(" ",end=" ")
  for k in range(n-i):
    print("*",end=" ")
  print()

#equilateral triangle

n = int(input("enter number of rows:"))
for i in range(n):
 for j in range(n-i):
  print(" ",end=" ")
 for j in range(i+1):
  print("*",end=" ")
 for j in range(i):
  print("*",end=" ")
 print()

#combining two patterns
n = int(input("enter number of rows:"))
for i in range(n):
  for j in range(n-i):
    print(" ",end=" ")
  for j in range(i+1):
    print("*",end=" ")
  for j in range(i+1):
    print("*",end=" ")
  print()

#inverted equilateral triangle
n = int(input("enter number of rows:"))
for i in range(n):
  for j in range(i):
    print(" ",end=" ")
  for j in range(n-i):
    print("*",end=" ")
  for j in range(n-i-1):
    print("*",end=" ")
  print()

#inverted combined triangle
n = int(input("enter number of rows:"))
for i in range(n):
  for j in range(i):
    print(" ",end=" ")
  for j in range(n-i):
    print("*",end=" ")
  for j in range(n-i):
    print("*",end=" ")
  print()