# -*- coding: utf-8 -*-
"""dict of subjects

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1pbQ1q8Zo3AUcLd5hbf3j02iJ3hiDyc
"""

n =100
for i in range(100):
 print(n,end=",")
 n=  n-1

n =1
for i in range(100):
 print(n,end=",")
 n=  n+1

n = int(input("enter a number to get its multiplication table: "))
a = 1
while(a<11):
  print(n , 'x', a , '=', n*a)
  a = a+1

list = [1,4,9,16,25,36,49,64,81,100]
x = int(input("enter a number from the list to search: "))
found = False
for i in range(len(list)):
  if(list[i]==x):
    print("number found")
    found = True
    break
if not found:
  print("number not found")

#sum of 1st n numbers using while
n = int(input("enter a number: "))
sum =0 #intially
a = n
while(a>0): #loop doesnt run if a becomes neg
  sum = sum +a
  a = a-1
print(sum)

# fact of a number using for
n = int(input("enter a number: "))
fact =1
for i in range(1,n+1):
 fact = fact*i
print(fact)

